name: Build Route Design Pro APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Installer les dependances
        run: flutter pub get

      - name: Verifier le projet
        run: flutter analyze

      - name: Construire l APK
        run: flutter build apk --release

      - name: Publier l APK
        uses: actions/upload-artifact@v4
        with:
          name: route-design-pro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
